### PR TITLE
Change cypher to cipher

### PR DESCRIPTION
**Pull request by Crafter6432**
Even though cypher isn't linguistically incorrect, it's still not commonly used in relation with crypto and cloud thus cause hard to find bugs as most people who don't copy & paste the parameters would type cipher instead of cypher.

Whoops, that uid thing shouldn't be in there wrong branch :/

### CODE REVIEW

**Comment by ktk** [comment]
Ah shit it did merge the UID one too. Was there a reason for this one?

**Comment by Crafter6432** [comment]
Somehow there was no user named hitch, so I tried to create one which failed because 999 was already in use

```
bash-4.3# adduser -h /var/lib/hitch -s /sbin/nologin -u 999 -D hitch
adduser: uid '999' in use
bash-4.3# cat /etc/passwd | grep 999
bash-4.3# cat /etc/passwd
root:x:0:0:root:/root:/bin/ash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
news:x:9:13:news:/usr/lib/news:/sbin/nologin
uucp:x:10:14:uucp:/var/spool/uucppublic:/sbin/nologin
operator:x:11:0:operator:/root:/bin/sh
man:x:13:15:man:/usr/man:/sbin/nologin
postmaster:x:14:12:postmaster:/var/spool/mail:/sbin/nologin
cron:x:16:16:cron:/var/spool/cron:/sbin/nologin
ftp:x:21:21::/var/lib/ftp:/sbin/nologin
sshd:x:22:22:sshd:/dev/null:/sbin/nologin
at:x:25:25:at:/var/spool/cron/atjobs:/sbin/nologin
squid:x:31:31:Squid:/var/cache/squid:/sbin/nologin
xfs:x:33:33:X Font Server:/etc/X11/fs:/sbin/nologin
games:x:35:35:games:/usr/games:/sbin/nologin
postgres:x:70:70::/var/lib/postgresql:/bin/sh
nut:x:84:84:nut:/var/state/nut:/sbin/nologin
cyrus:x:85:12::/usr/cyrus:/sbin/nologin
vpopmail:x:89:89::/var/vpopmail:/sbin/nologin
ntp:x:123:123:NTP:/var/empty:/sbin/nologin
smmsp:x:209:209:smmsp:/var/spool/mqueue:/sbin/nologin
guest:x:405:100:guest:/dev/null:/sbin/nologin
nobody:x:65534:65534:nobody:/:/sbin/nologin
```

**Comment by ktk** [comment]
Interesting, does it work properly now? If so I leave it like this

**Comment by Crafter6432** [comment]
Seems to work :)

**Pull request merged**
